// <auto-generated />
using System;
using Global_Logistics_Management_System___ST10439898.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Global_Logistics_Management_System___ST10439898.Migrations
{
    [DbContext(typeof(GLMSContext))]
    [Migration("20260422004609_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.Client", b =>
                {
                    b.Property<int>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientID"));

                    b.Property<string>("clientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.Contract", b =>
                {
                    b.Property<int>("contractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contractID"));

                    b.Property<int>("clientID")
                        .HasColumnType("int");

                    b.Property<int>("contractStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serviceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("signedAgreementPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("contractID");

                    b.HasIndex("clientID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.ServiceRequest", b =>
                {
                    b.Property<int>("requestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestID"));

                    b.Property<decimal>("CostinZAR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("contractID")
                        .HasColumnType("int");

                    b.Property<int>("requestStatus")
                        .HasColumnType("int");

                    b.HasKey("requestID");

                    b.HasIndex("contractID");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.Contract", b =>
                {
                    b.HasOne("Global_Logistics_Management_System___ST10439898.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("clientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.ServiceRequest", b =>
                {
                    b.HasOne("Global_Logistics_Management_System___ST10439898.Models.Contract", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("contractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Global_Logistics_Management_System___ST10439898.Models.Contract", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
